# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task
  pod 'SwiftLint'
  
  target 'TaskTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftLint'
    
  end

end
